# Generated by Django 5.1.3 on 2024-12-24 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='area',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='historique',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='region',
        ),
        migrations.AddField(
            model_name='parcelle',
            name='iduu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='properties',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='shape_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='shape_leng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='sum_superf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='theme',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='code_bdn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
