# Generated by Django 5.1.3 on 2025-03-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_remove_parcelle_area_remove_parcelle_historique_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='en cours', max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
